name: Alma build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.target.runner }}
    strategy:
      matrix:
        target:
          - runtime: win-x64
            runner: windows-latest
            name: windows
            outputname: Alma.exe
          - runtime: linux-x64
            runner: ubuntu-latest
            name: linux
            outputname: Alma
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: Restore dependencies
        run: dotnet restore src/Alma
      - name: Build
        run: dotnet publish -c Release -p:PublishAot=true -r ${{ matrix.target.runtime }} -o app/ src/Alma
      - uses: actions/upload-artifact@v3
        with:
          name: alma-${{ matrix.target.name }}
          path: app/${{ matrix.target.outputname }}
  
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: alma-windows
          path: app/windows/
      - uses: actions/download-artifact@v3
        with:
          name: alma-linux
          path: app/linux/
    
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: app
