name: Alma build

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.target.runner }}
    strategy:
      matrix:
        target:
          - runtime: win-x64
            runner: windows-latest
            name: windows
          - runtime: linux-x64
            runner: ubuntu-latest
            name: linux
    steps:
      - uses: actions/checkout@v3
      - name: Setup dotnet
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.0.x'
      - name: Restore dependencies
        run: dotnet restore src/Alma
      - name: Build
        run: dotnet publish -r ${{ matrix.target.runtime }} -o app/ src/Alma
      - uses: actions/upload-artifact@v3
        with:
          name: alma-${{ matrix.target.name }}
          path: app/
